theme: minima
title: "Clouds in Sky"
description: "There are as many places to try as clouds in the sky"
author: "SpaceClouds"

baseurl: /clouds-in-sky
excerpt_separator: <!--more-->

header_pages: 
  - about.md
  - bubble-tea.html
  - food.html
  - ice-cream.html
  - categories.html
